# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(755, 891)
        self.pushButton_pyinstaller = QtWidgets.QPushButton(Form)
        self.pushButton_pyinstaller.setGeometry(QtCore.QRect(610, 60, 91, 23))
        self.pushButton_pyinstaller.setObjectName("pushButton_pyinstaller")
        self.lineEdit_pyinstaller = QtWidgets.QLineEdit(Form)
        self.lineEdit_pyinstaller.setGeometry(QtCore.QRect(50, 60, 551, 20))
        self.lineEdit_pyinstaller.setObjectName("lineEdit_pyinstaller")
        self.lineEdit_ico = QtWidgets.QLineEdit(Form)
        self.lineEdit_ico.setGeometry(QtCore.QRect(50, 150, 551, 20))
        self.lineEdit_ico.setObjectName("lineEdit_ico")
        self.pushButton_ico = QtWidgets.QPushButton(Form)
        self.pushButton_ico.setGeometry(QtCore.QRect(610, 150, 91, 23))
        self.pushButton_ico.setObjectName("pushButton_ico")
        self.pushButton_temp_path = QtWidgets.QPushButton(Form)
        self.pushButton_temp_path.setGeometry(QtCore.QRect(610, 90, 91, 23))
        self.pushButton_temp_path.setObjectName("pushButton_temp_path")
        self.lineEdit_temp_path = QtWidgets.QLineEdit(Form)
        self.lineEdit_temp_path.setGeometry(QtCore.QRect(50, 90, 551, 20))
        self.lineEdit_temp_path.setObjectName("lineEdit_temp_path")
        self.pushButton_file = QtWidgets.QPushButton(Form)
        self.pushButton_file.setGeometry(QtCore.QRect(610, 120, 91, 23))
        self.pushButton_file.setObjectName("pushButton_file")
        self.lineEdit_file = QtWidgets.QLineEdit(Form)
        self.lineEdit_file.setGeometry(QtCore.QRect(50, 120, 551, 20))
        self.lineEdit_file.setObjectName("lineEdit_file")
        self.checkBox_single = QtWidgets.QCheckBox(Form)
        self.checkBox_single.setGeometry(QtCore.QRect(50, 210, 161, 31))
        self.checkBox_single.setChecked(True)
        self.checkBox_single.setObjectName("checkBox_single")
        self.checkBox_clear = QtWidgets.QCheckBox(Form)
        self.checkBox_clear.setGeometry(QtCore.QRect(270, 210, 161, 31))
        self.checkBox_clear.setChecked(True)
        self.checkBox_clear.setObjectName("checkBox_clear")
        self.textEdit_data_paths = QtWidgets.QTextEdit(Form)
        self.textEdit_data_paths.setGeometry(QtCore.QRect(50, 250, 651, 71))
        self.textEdit_data_paths.setObjectName("textEdit_data_paths")
        self.textEdit_third_paths = QtWidgets.QTextEdit(Form)
        self.textEdit_third_paths.setGeometry(QtCore.QRect(50, 410, 651, 71))
        self.textEdit_third_paths.setObjectName("textEdit_third_paths")
        self.pushButton_start = QtWidgets.QPushButton(Form)
        self.pushButton_start.setGeometry(QtCore.QRect(600, 530, 101, 41))
        self.pushButton_start.setObjectName("pushButton_start")
        self.textEdit_log = QtWidgets.QTextEdit(Form)
        self.textEdit_log.setGeometry(QtCore.QRect(50, 580, 651, 291))
        self.textEdit_log.setObjectName("textEdit_log")
        self.label_title = QtWidgets.QLabel(Form)
        self.label_title.setGeometry(QtCore.QRect(150, -10, 501, 81))
        self.label_title.setStyleSheet("font: 22pt \"黑体\";\n"
"text-decoration: underline;")
        self.label_title.setObjectName("label_title")
        self.textEdit_binary_paths = QtWidgets.QTextEdit(Form)
        self.textEdit_binary_paths.setGeometry(QtCore.QRect(50, 330, 651, 71))
        self.textEdit_binary_paths.setObjectName("textEdit_binary_paths")
        self.checkBox_cmd = QtWidgets.QCheckBox(Form)
        self.checkBox_cmd.setGeometry(QtCore.QRect(480, 210, 161, 31))
        self.checkBox_cmd.setChecked(True)
        self.checkBox_cmd.setObjectName("checkBox_cmd")
        self.lineEdit_name = QtWidgets.QLineEdit(Form)
        self.lineEdit_name.setGeometry(QtCore.QRect(50, 530, 113, 41))
        self.lineEdit_name.setStyleSheet("border-bottom: 3px solid black;\n"
"border-top: none;\n"
"font: 12pt \"黑体\";")
        self.lineEdit_name.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_name.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.lineEdit_hidden_import = QtWidgets.QLineEdit(Form)
        self.lineEdit_hidden_import.setGeometry(QtCore.QRect(50, 490, 651, 31))
        self.lineEdit_hidden_import.setObjectName("lineEdit_hidden_import")
        self.pushButton_splash = QtWidgets.QPushButton(Form)
        self.pushButton_splash.setGeometry(QtCore.QRect(610, 180, 91, 23))
        self.pushButton_splash.setObjectName("pushButton_splash")
        self.lineEdit_splash = QtWidgets.QLineEdit(Form)
        self.lineEdit_splash.setGeometry(QtCore.QRect(50, 180, 551, 20))
        self.lineEdit_splash.setObjectName("lineEdit_splash")
        self.lineEdit_additional_instruction_set = QtWidgets.QLineEdit(Form)
        self.lineEdit_additional_instruction_set.setGeometry(QtCore.QRect(190, 530, 391, 41))
        self.lineEdit_additional_instruction_set.setStyleSheet("border-bottom: 3px solid black;\n"
"border-top: none;\n"
"font: 12pt \"黑体\";")
        self.lineEdit_additional_instruction_set.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_additional_instruction_set.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.lineEdit_additional_instruction_set.setObjectName("lineEdit_additional_instruction_set")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_pyinstaller.setText(_translate("Form", "*Select"))
        self.lineEdit_pyinstaller.setPlaceholderText(_translate("Form", "Pyinstaller.exe 路径"))
        self.lineEdit_ico.setPlaceholderText(_translate("Form", "ico 路径"))
        self.pushButton_ico.setText(_translate("Form", "Select"))
        self.pushButton_temp_path.setText(_translate("Form", "*Select"))
        self.lineEdit_temp_path.setPlaceholderText(_translate("Form", "temp_path 路径"))
        self.pushButton_file.setText(_translate("Form", "*Select"))
        self.lineEdit_file.setPlaceholderText(_translate("Form", "项目入口文件"))
        self.checkBox_single.setText(_translate("Form", "是否开启单文件模式"))
        self.checkBox_clear.setText(_translate("Form", "是否清理临时文件"))
        self.textEdit_data_paths.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textEdit_data_paths.setPlaceholderText(_translate("Form", "图片，音视频等资源文件目录"))
        self.textEdit_third_paths.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textEdit_third_paths.setPlaceholderText(_translate("Form", "第三方资源包目录"))
        self.pushButton_start.setText(_translate("Form", "开始打包"))
        self.textEdit_log.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">日志</p></body></html>"))
        self.label_title.setText(_translate("Form", "Pyinstaller 打包 Pyhton 小工具"))
        self.textEdit_binary_paths.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textEdit_binary_paths.setPlaceholderText(_translate("Form", "二进制文件目录"))
        self.checkBox_cmd.setText(_translate("Form", "是否隐藏命令行窗口"))
        self.lineEdit_name.setPlaceholderText(_translate("Form", "EXE 名"))
        self.lineEdit_hidden_import.setPlaceholderText(_translate("Form", "一些无法导入的系统模块,多个模块间用 ”，“分隔"))
        self.pushButton_splash.setText(_translate("Form", "Select"))
        self.lineEdit_splash.setPlaceholderText(_translate("Form", "启动动画 路径（必须是.png格式）"))
        self.lineEdit_additional_instruction_set.setPlaceholderText(_translate("Form", "附加指令集"))
